version: '3.8'

services:
  apache:
    image: httpd:latest
    container_name: meu_apache
    ports:
      - "80:80"
    volumes:
      - /compose/html:/usr/local/apache2/htdocs
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
